name: themebuilder
description: Flutter Theme Builder
publish_to: 'none'
version: 1.0.0
authors: 
  - Dhruvil Patel (Github - dhruvilp)

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
  - assets/

  fonts:
  - family: Quicksand
    fonts:
      - asset: assets/fonts/Quicksand-Medium.ttf
